version: '3.8'

services:
  app:
    build: .
    container_name: history-stock-api-nestjs
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run start:dev
